### ISSUE TITLE
installing pythonocc-utils in pythonocc conda environment: "no module named Common"

### ISSUE THREAD

**Issue by calocedrus** [tpaviot/pythonocc-utils#13]
Hello, I have pythonocc-core installed in an anaconda environment and it is a pleasure to use (though with a very steep learning curve as I had never manipulated CAD files/drawing before and am few months old in python).
`conda create -n pythonocc -c pythonocc -c dlr-sc pythonocc-core==0.17.2 python=3`
In my activated pythonocc environment
`source activate pythonocc`
I've cloned pythonocc-utils, navigated to its root directory and:
`pip install ./pythonocc-utils`
I can verify that OCCutils is correctly in my current conda environment:
`conda list`
does show me this line
`OCCUtils-0.1                    dev                       <pip>`
But in a python console, 
`>>> import OCCUtils`
returns
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Python/DataVisualization/CADRelated/pythonocc-utils-master/OCCUtils/__init__.py", line 1, in <module>
    from Common import get_boundingbox
ImportError: No module named 'Common'
```
same if I try `import Common`.
So I've uninstalled OCCutils
`pip uninstall OCCutils`
and tried 
`python setup.py install`
but with the same outcome (both installation methods seem to be equivalent).
It's much more likely that I'm not correctly installing the module rather than an issue with the module itself, but could you please help or comment on my issue?

**Comment by calocedrus** [comment]
Some more precisions:
1) OCCUtils is present in my anaconda3 site-package environment
2) if I try to import OCCUtils from the root directory of pythonocc-utils-master, I get:
```File "<stdin>", line 1, in <module>
  File "~/Python/DataVisualization/CADRelated/pythonocc-utils-master/OCCUtils/__init__.py", line 1, in <module>
    from Common import get_boundingbox
ImportError: No module named 'Common'
```
3) if I try to import it from anywhere else outside that directory I get:
```File "<stdin>", line 1, in <module>
  File "~/anaconda3/envs/pythonocc/lib/python3.5/site-packages/OCCUtils/__init__.py", line 1, in <module>
    from Common import get_boundingbox
ImportError: No module named 'Common'
```
In 2), python searched for OCCUtils in the pythonocc-utils-master root directory which contains an OCCUtils directory, while in 3) it searched in the anaconda3 pythonocc environment directory. 

I have solved the `No module named 'Common'` by deleting the content of `anaconda3/envs/pythonocc/lib/python3.5/site-packages/OCCUtils/__init__.py` (i.e. `__init__.py` is empty). Now I can import OCCUtils. But I don't know why it worked!

**Comment by selvakarna** [comment]
inside package does not like OCCDataExange? How to install properly in Linux ?
